import{i as a,S as f}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const l=document.querySelector(".form"),u=document.querySelector(".gallery"),p=document.querySelector(".loader");function m(){p.classList.remove("hidden")}function c(){p.classList.add("hidden")}l.addEventListener("submit",d);function d(n){n.preventDefault(),u.innerHTML="";const o=n.target.elements.input.value,s="42276910-5dbc0617c597b0712888fd711";if(o==="")return a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});m(),g(s,o).then(t=>{h(t),c()}).catch(t=>{console.error("Error fetching photos:",t),c()}).finally(()=>l.reset())}function g(n,o){const s="https://pixabay.com",t="/api/",e=`?key=${n}&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`,r=s+t+e;return fetch(r).then(i=>i.json())}function h(n){if(n.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const o=n.hits.map(t=>`<li class="gallery-item">
             <a class="gallery-link" href="${t.webformatURL}">
            <img class="gallery-image" src="${t.largeImageURL}" alt="${t.tags}" />
            </a>
            <p><b>Likes: </b>${t.likes}</p>
            <p><b>Views: </b>${t.views}</p>
            <p><b>Comments: </b>${t.comments}</p> 
            <p><b>Downloads: </b>${t.downloads}</p>
        </li>`).join("");u.insertAdjacentHTML("afterbegin",o),new f(".gallery a",y).refresh()}const y={captions:!0,captionType:"attr",captionSelector:"img",captionsData:"alt",captionPosition:"bottom",captionDelay:250};
//# sourceMappingURL=commonHelpers.js.map
